### ISSUE TITLE
Still have any plan to release the code? 

### ISSUE THREAD

**Issue by lilligao** [JeffWang987/DriveDreamer#5]
Hi, I read the paper and it's really inspiring. It would be really cool if you could release the code! Thank you so much!

**Comment by JeffWang987** [comment]
Sorry for the late reply. We have released the research code for DriveDreamer. Additionally, we have reframed our code to provide greater flexibility and customization. Now, users can define data configurations, distributed training settings, model parameters, visualizations, and more directly within the configuration files. We hope this will facilitate easier experimentation and adaptation of our framework.
