### ISSUE TITLE
When to release the code？

### ISSUE THREAD

**Issue by sugersyy** [JeffWang987/DriveDreamer#6]
Thanks for your excellent work.When will the code be opened? Thank you very much.

**Comment by JeffWang987** [comment]
Sorry for the late reply. We have released the research code for DriveDreamer. Additionally, we have reframed our code to provide greater flexibility and customization. Now, users can define data configurations, distributed training settings, model parameters, visualizations, and more directly within the configuration files. We hope this will facilitate easier experimentation and adaptation of our framework.
