### ISSUE TITLE
about training setp.

### ISSUE THREAD

**Issue by WuZhongQing** [JeffWang987/DriveDreamer#8]
hi, thanks for your open source , and you said there has two step in training video, and i want to ask if this means that i have to training image first, then training video ?

**Comment by JeffWang987** [comment]
It's recommended to train stage-1 and initialize stage-2. This will accelerate training convergence and save time.
Skip stage-1 is also OK, but the cost is to train more epochs in stage-2.

**Comment by WuZhongQing** [comment]
> It's recommended to train stage-1 and initialize stage-2. This will accelerate training convergence and save time. Skip stage-1 is also OK, but the cost is to train more epochs in stage-2.

thanks for your reply~

**Comment by jlq379130258** [comment]
> It's recommended to train stage-1 and initialize stage-2. This will accelerate training convergence and save time. Skip stage-1 is also OK, but the cost is to train more epochs in stage-2.

hi, I did not find any codes about action predict. May I ask is it released yet? or any plan to release. Thank you very much!
